### PR TITLE
Harrison Brock (Programming Assignment 1 & 2)

### PR DESCRIPTION
**Pull request by harrisonbrock**
I think I have everything done but I'm sure I'm missing something.

### CODE REVIEW

**Comment by harrisonbrock** [comment]
I almost have the inline-box done.

**Comment by kiadorii** [comment]
Great job with flex, it just shows how awesome it is! You definitely have inline-block almost complete. Just a few minor details need to be adjusted. The inline-block portion was created in order for you to gain experience and understanding. Also, great commit messages! Let the channel or DM me if you have any questions as usual! 👍

**Comment by harrisonbrock** [comment]
I think this cleans it up

**Comment by kiadorii** [comment]
Your inline-block is looking wonderful! You definitely cleaned a lot of it! I'm not sure if you forgot but your contact is not aligned to the center.

**Pull request closed without merging**
