### PR TITLE
Project 1 Website Edits

### PR DESCRIPTION
**Pull request by Anthony-Calderaro**
Anthony Calderaro changes to the format to make the base HTML file look like the great-idea-example.jpg file.

### CODE REVIEW

**Comment by DonnieU** [comment]
Everything looks proper except for the "Get Started" button being out of alignment. Great job!

**Comment by Anthony-Calderaro** [comment]
Anthony's attempt at recreating the HTML and CSS styling from scratch while using flexbox. I was a bit lazy to link the google fonts, so i just used cursive - please be RELENTLESS with your feedback. I am hungry to learn and promise not to take offense.

**Comment by Anthony-Calderaro** [comment]
Anthony's attempt at recreating the HTML and CSS styling from scratch while using flexbox. I was a bit lazy to link the google fonts, so i just used cursive - please be RELENTLESS with your feedback. I am hungry to learn and promise not to take offense.

**Comment by Anthony-Calderaro** [comment]
Anthony's attempt at recreating the HTML and CSS styling from scratch while using flexbox. I was a bit lazy to link the google fonts, so i just used cursive - please be RELENTLESS with your feedback. I am hungry to learn and promise not to take offense.

**Pull request closed without merging**
